/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JudgeScoringRouteRouteImport } from './routes/judge/scoring/route'
import { Route as AdminConsoleRouteRouteImport } from './routes/admin/console/route'
import { Route as JudgeScoringIndexRouteImport } from './routes/judge/scoring/index'
import { Route as JudgeLoginIndexRouteImport } from './routes/judge/login/index'
import { Route as AdminLoginIndexRouteImport } from './routes/admin/login/index'
import { Route as AdminConsoleIndexRouteImport } from './routes/admin/console/index'
import { Route as AdminConsolePhasesRouteImport } from './routes/admin/console/phases'
import { Route as AdminConsoleJudgesRouteImport } from './routes/admin/console/judges'
import { Route as AdminConsoleDashboardRouteImport } from './routes/admin/console/dashboard'
import { Route as AdminConsoleCollegesRouteImport } from './routes/admin/console/colleges'
import { Route as AdminConsoleCandidatesRouteImport } from './routes/admin/console/candidates'
import { Route as AdminConsoleSegmentsIndexRouteImport } from './routes/admin/console/segments/index'
import { Route as AdminConsolePageantsIndexRouteImport } from './routes/admin/console/pageants/index'
import { Route as AdminConsoleAwardsIndexRouteImport } from './routes/admin/console/awards/index'
import { Route as AdminConsoleAwardsAddRouteImport } from './routes/admin/console/awards/add'
import { Route as AdminConsoleSegmentsSegmentIdScoresRouteImport } from './routes/admin/console/segments/$segmentId.scores'
import { Route as AdminConsoleSegmentsSegmentIdQualifiedRouteImport } from './routes/admin/console/segments/$segmentId.qualified'
import { Route as AdminConsoleSegmentsSegmentIdEditRouteImport } from './routes/admin/console/segments/$segmentId.edit'
import { Route as AdminConsolePageantsPageantIdSoftResetRouteImport } from './routes/admin/console/pageants/$pageantId.soft-reset'
import { Route as AdminConsoleAwardsAwardIdResultsRouteImport } from './routes/admin/console/awards/$awardId.results'
import { Route as AdminConsoleAwardsAwardIdEditRouteImport } from './routes/admin/console/awards/$awardId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JudgeScoringRouteRoute = JudgeScoringRouteRouteImport.update({
  id: '/judge/scoring',
  path: '/judge/scoring',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConsoleRouteRoute = AdminConsoleRouteRouteImport.update({
  id: '/admin/console',
  path: '/admin/console',
  getParentRoute: () => rootRouteImport,
} as any)
const JudgeScoringIndexRoute = JudgeScoringIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => JudgeScoringRouteRoute,
} as any)
const JudgeLoginIndexRoute = JudgeLoginIndexRouteImport.update({
  id: '/judge/login/',
  path: '/judge/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginIndexRoute = AdminLoginIndexRouteImport.update({
  id: '/admin/login/',
  path: '/admin/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConsoleIndexRoute = AdminConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminConsoleRouteRoute,
} as any)
const AdminConsolePhasesRoute = AdminConsolePhasesRouteImport.update({
  id: '/phases',
  path: '/phases',
  getParentRoute: () => AdminConsoleRouteRoute,
} as any)
const AdminConsoleJudgesRoute = AdminConsoleJudgesRouteImport.update({
  id: '/judges',
  path: '/judges',
  getParentRoute: () => AdminConsoleRouteRoute,
} as any)
const AdminConsoleDashboardRoute = AdminConsoleDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminConsoleRouteRoute,
} as any)
const AdminConsoleCollegesRoute = AdminConsoleCollegesRouteImport.update({
  id: '/colleges',
  path: '/colleges',
  getParentRoute: () => AdminConsoleRouteRoute,
} as any)
const AdminConsoleCandidatesRoute = AdminConsoleCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => AdminConsoleRouteRoute,
} as any)
const AdminConsoleSegmentsIndexRoute =
  AdminConsoleSegmentsIndexRouteImport.update({
    id: '/segments/',
    path: '/segments/',
    getParentRoute: () => AdminConsoleRouteRoute,
  } as any)
const AdminConsolePageantsIndexRoute =
  AdminConsolePageantsIndexRouteImport.update({
    id: '/pageants/',
    path: '/pageants/',
    getParentRoute: () => AdminConsoleRouteRoute,
  } as any)
const AdminConsoleAwardsIndexRoute = AdminConsoleAwardsIndexRouteImport.update({
  id: '/awards/',
  path: '/awards/',
  getParentRoute: () => AdminConsoleRouteRoute,
} as any)
const AdminConsoleAwardsAddRoute = AdminConsoleAwardsAddRouteImport.update({
  id: '/awards/add',
  path: '/awards/add',
  getParentRoute: () => AdminConsoleRouteRoute,
} as any)
const AdminConsoleSegmentsSegmentIdScoresRoute =
  AdminConsoleSegmentsSegmentIdScoresRouteImport.update({
    id: '/segments/$segmentId/scores',
    path: '/segments/$segmentId/scores',
    getParentRoute: () => AdminConsoleRouteRoute,
  } as any)
const AdminConsoleSegmentsSegmentIdQualifiedRoute =
  AdminConsoleSegmentsSegmentIdQualifiedRouteImport.update({
    id: '/segments/$segmentId/qualified',
    path: '/segments/$segmentId/qualified',
    getParentRoute: () => AdminConsoleRouteRoute,
  } as any)
const AdminConsoleSegmentsSegmentIdEditRoute =
  AdminConsoleSegmentsSegmentIdEditRouteImport.update({
    id: '/segments/$segmentId/edit',
    path: '/segments/$segmentId/edit',
    getParentRoute: () => AdminConsoleRouteRoute,
  } as any)
const AdminConsolePageantsPageantIdSoftResetRoute =
  AdminConsolePageantsPageantIdSoftResetRouteImport.update({
    id: '/pageants/$pageantId/soft-reset',
    path: '/pageants/$pageantId/soft-reset',
    getParentRoute: () => AdminConsoleRouteRoute,
  } as any)
const AdminConsoleAwardsAwardIdResultsRoute =
  AdminConsoleAwardsAwardIdResultsRouteImport.update({
    id: '/awards/$awardId/results',
    path: '/awards/$awardId/results',
    getParentRoute: () => AdminConsoleRouteRoute,
  } as any)
const AdminConsoleAwardsAwardIdEditRoute =
  AdminConsoleAwardsAwardIdEditRouteImport.update({
    id: '/awards/$awardId/edit',
    path: '/awards/$awardId/edit',
    getParentRoute: () => AdminConsoleRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/console': typeof AdminConsoleRouteRouteWithChildren
  '/judge/scoring': typeof JudgeScoringRouteRouteWithChildren
  '/admin/console/candidates': typeof AdminConsoleCandidatesRoute
  '/admin/console/colleges': typeof AdminConsoleCollegesRoute
  '/admin/console/dashboard': typeof AdminConsoleDashboardRoute
  '/admin/console/judges': typeof AdminConsoleJudgesRoute
  '/admin/console/phases': typeof AdminConsolePhasesRoute
  '/admin/console/': typeof AdminConsoleIndexRoute
  '/admin/login': typeof AdminLoginIndexRoute
  '/judge/login': typeof JudgeLoginIndexRoute
  '/judge/scoring/': typeof JudgeScoringIndexRoute
  '/admin/console/awards/add': typeof AdminConsoleAwardsAddRoute
  '/admin/console/awards': typeof AdminConsoleAwardsIndexRoute
  '/admin/console/pageants': typeof AdminConsolePageantsIndexRoute
  '/admin/console/segments': typeof AdminConsoleSegmentsIndexRoute
  '/admin/console/awards/$awardId/edit': typeof AdminConsoleAwardsAwardIdEditRoute
  '/admin/console/awards/$awardId/results': typeof AdminConsoleAwardsAwardIdResultsRoute
  '/admin/console/pageants/$pageantId/soft-reset': typeof AdminConsolePageantsPageantIdSoftResetRoute
  '/admin/console/segments/$segmentId/edit': typeof AdminConsoleSegmentsSegmentIdEditRoute
  '/admin/console/segments/$segmentId/qualified': typeof AdminConsoleSegmentsSegmentIdQualifiedRoute
  '/admin/console/segments/$segmentId/scores': typeof AdminConsoleSegmentsSegmentIdScoresRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/console/candidates': typeof AdminConsoleCandidatesRoute
  '/admin/console/colleges': typeof AdminConsoleCollegesRoute
  '/admin/console/dashboard': typeof AdminConsoleDashboardRoute
  '/admin/console/judges': typeof AdminConsoleJudgesRoute
  '/admin/console/phases': typeof AdminConsolePhasesRoute
  '/admin/console': typeof AdminConsoleIndexRoute
  '/admin/login': typeof AdminLoginIndexRoute
  '/judge/login': typeof JudgeLoginIndexRoute
  '/judge/scoring': typeof JudgeScoringIndexRoute
  '/admin/console/awards/add': typeof AdminConsoleAwardsAddRoute
  '/admin/console/awards': typeof AdminConsoleAwardsIndexRoute
  '/admin/console/pageants': typeof AdminConsolePageantsIndexRoute
  '/admin/console/segments': typeof AdminConsoleSegmentsIndexRoute
  '/admin/console/awards/$awardId/edit': typeof AdminConsoleAwardsAwardIdEditRoute
  '/admin/console/awards/$awardId/results': typeof AdminConsoleAwardsAwardIdResultsRoute
  '/admin/console/pageants/$pageantId/soft-reset': typeof AdminConsolePageantsPageantIdSoftResetRoute
  '/admin/console/segments/$segmentId/edit': typeof AdminConsoleSegmentsSegmentIdEditRoute
  '/admin/console/segments/$segmentId/qualified': typeof AdminConsoleSegmentsSegmentIdQualifiedRoute
  '/admin/console/segments/$segmentId/scores': typeof AdminConsoleSegmentsSegmentIdScoresRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/console': typeof AdminConsoleRouteRouteWithChildren
  '/judge/scoring': typeof JudgeScoringRouteRouteWithChildren
  '/admin/console/candidates': typeof AdminConsoleCandidatesRoute
  '/admin/console/colleges': typeof AdminConsoleCollegesRoute
  '/admin/console/dashboard': typeof AdminConsoleDashboardRoute
  '/admin/console/judges': typeof AdminConsoleJudgesRoute
  '/admin/console/phases': typeof AdminConsolePhasesRoute
  '/admin/console/': typeof AdminConsoleIndexRoute
  '/admin/login/': typeof AdminLoginIndexRoute
  '/judge/login/': typeof JudgeLoginIndexRoute
  '/judge/scoring/': typeof JudgeScoringIndexRoute
  '/admin/console/awards/add': typeof AdminConsoleAwardsAddRoute
  '/admin/console/awards/': typeof AdminConsoleAwardsIndexRoute
  '/admin/console/pageants/': typeof AdminConsolePageantsIndexRoute
  '/admin/console/segments/': typeof AdminConsoleSegmentsIndexRoute
  '/admin/console/awards/$awardId/edit': typeof AdminConsoleAwardsAwardIdEditRoute
  '/admin/console/awards/$awardId/results': typeof AdminConsoleAwardsAwardIdResultsRoute
  '/admin/console/pageants/$pageantId/soft-reset': typeof AdminConsolePageantsPageantIdSoftResetRoute
  '/admin/console/segments/$segmentId/edit': typeof AdminConsoleSegmentsSegmentIdEditRoute
  '/admin/console/segments/$segmentId/qualified': typeof AdminConsoleSegmentsSegmentIdQualifiedRoute
  '/admin/console/segments/$segmentId/scores': typeof AdminConsoleSegmentsSegmentIdScoresRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/console'
    | '/judge/scoring'
    | '/admin/console/candidates'
    | '/admin/console/colleges'
    | '/admin/console/dashboard'
    | '/admin/console/judges'
    | '/admin/console/phases'
    | '/admin/console/'
    | '/admin/login'
    | '/judge/login'
    | '/judge/scoring/'
    | '/admin/console/awards/add'
    | '/admin/console/awards'
    | '/admin/console/pageants'
    | '/admin/console/segments'
    | '/admin/console/awards/$awardId/edit'
    | '/admin/console/awards/$awardId/results'
    | '/admin/console/pageants/$pageantId/soft-reset'
    | '/admin/console/segments/$segmentId/edit'
    | '/admin/console/segments/$segmentId/qualified'
    | '/admin/console/segments/$segmentId/scores'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/console/candidates'
    | '/admin/console/colleges'
    | '/admin/console/dashboard'
    | '/admin/console/judges'
    | '/admin/console/phases'
    | '/admin/console'
    | '/admin/login'
    | '/judge/login'
    | '/judge/scoring'
    | '/admin/console/awards/add'
    | '/admin/console/awards'
    | '/admin/console/pageants'
    | '/admin/console/segments'
    | '/admin/console/awards/$awardId/edit'
    | '/admin/console/awards/$awardId/results'
    | '/admin/console/pageants/$pageantId/soft-reset'
    | '/admin/console/segments/$segmentId/edit'
    | '/admin/console/segments/$segmentId/qualified'
    | '/admin/console/segments/$segmentId/scores'
  id:
    | '__root__'
    | '/'
    | '/admin/console'
    | '/judge/scoring'
    | '/admin/console/candidates'
    | '/admin/console/colleges'
    | '/admin/console/dashboard'
    | '/admin/console/judges'
    | '/admin/console/phases'
    | '/admin/console/'
    | '/admin/login/'
    | '/judge/login/'
    | '/judge/scoring/'
    | '/admin/console/awards/add'
    | '/admin/console/awards/'
    | '/admin/console/pageants/'
    | '/admin/console/segments/'
    | '/admin/console/awards/$awardId/edit'
    | '/admin/console/awards/$awardId/results'
    | '/admin/console/pageants/$pageantId/soft-reset'
    | '/admin/console/segments/$segmentId/edit'
    | '/admin/console/segments/$segmentId/qualified'
    | '/admin/console/segments/$segmentId/scores'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminConsoleRouteRoute: typeof AdminConsoleRouteRouteWithChildren
  JudgeScoringRouteRoute: typeof JudgeScoringRouteRouteWithChildren
  AdminLoginIndexRoute: typeof AdminLoginIndexRoute
  JudgeLoginIndexRoute: typeof JudgeLoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/judge/scoring': {
      id: '/judge/scoring'
      path: '/judge/scoring'
      fullPath: '/judge/scoring'
      preLoaderRoute: typeof JudgeScoringRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/console': {
      id: '/admin/console'
      path: '/admin/console'
      fullPath: '/admin/console'
      preLoaderRoute: typeof AdminConsoleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/judge/scoring/': {
      id: '/judge/scoring/'
      path: '/'
      fullPath: '/judge/scoring/'
      preLoaderRoute: typeof JudgeScoringIndexRouteImport
      parentRoute: typeof JudgeScoringRouteRoute
    }
    '/judge/login/': {
      id: '/judge/login/'
      path: '/judge/login'
      fullPath: '/judge/login'
      preLoaderRoute: typeof JudgeLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login/': {
      id: '/admin/login/'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/console/': {
      id: '/admin/console/'
      path: '/'
      fullPath: '/admin/console/'
      preLoaderRoute: typeof AdminConsoleIndexRouteImport
      parentRoute: typeof AdminConsoleRouteRoute
    }
    '/admin/console/phases': {
      id: '/admin/console/phases'
      path: '/phases'
      fullPath: '/admin/console/phases'
      preLoaderRoute: typeof AdminConsolePhasesRouteImport
      parentRoute: typeof AdminConsoleRouteRoute
    }
    '/admin/console/judges': {
      id: '/admin/console/judges'
      path: '/judges'
      fullPath: '/admin/console/judges'
      preLoaderRoute: typeof AdminConsoleJudgesRouteImport
      parentRoute: typeof AdminConsoleRouteRoute
    }
    '/admin/console/dashboard': {
      id: '/admin/console/dashboard'
      path: '/dashboard'
      fullPath: '/admin/console/dashboard'
      preLoaderRoute: typeof AdminConsoleDashboardRouteImport
      parentRoute: typeof AdminConsoleRouteRoute
    }
    '/admin/console/colleges': {
      id: '/admin/console/colleges'
      path: '/colleges'
      fullPath: '/admin/console/colleges'
      preLoaderRoute: typeof AdminConsoleCollegesRouteImport
      parentRoute: typeof AdminConsoleRouteRoute
    }
    '/admin/console/candidates': {
      id: '/admin/console/candidates'
      path: '/candidates'
      fullPath: '/admin/console/candidates'
      preLoaderRoute: typeof AdminConsoleCandidatesRouteImport
      parentRoute: typeof AdminConsoleRouteRoute
    }
    '/admin/console/segments/': {
      id: '/admin/console/segments/'
      path: '/segments'
      fullPath: '/admin/console/segments'
      preLoaderRoute: typeof AdminConsoleSegmentsIndexRouteImport
      parentRoute: typeof AdminConsoleRouteRoute
    }
    '/admin/console/pageants/': {
      id: '/admin/console/pageants/'
      path: '/pageants'
      fullPath: '/admin/console/pageants'
      preLoaderRoute: typeof AdminConsolePageantsIndexRouteImport
      parentRoute: typeof AdminConsoleRouteRoute
    }
    '/admin/console/awards/': {
      id: '/admin/console/awards/'
      path: '/awards'
      fullPath: '/admin/console/awards'
      preLoaderRoute: typeof AdminConsoleAwardsIndexRouteImport
      parentRoute: typeof AdminConsoleRouteRoute
    }
    '/admin/console/awards/add': {
      id: '/admin/console/awards/add'
      path: '/awards/add'
      fullPath: '/admin/console/awards/add'
      preLoaderRoute: typeof AdminConsoleAwardsAddRouteImport
      parentRoute: typeof AdminConsoleRouteRoute
    }
    '/admin/console/segments/$segmentId/scores': {
      id: '/admin/console/segments/$segmentId/scores'
      path: '/segments/$segmentId/scores'
      fullPath: '/admin/console/segments/$segmentId/scores'
      preLoaderRoute: typeof AdminConsoleSegmentsSegmentIdScoresRouteImport
      parentRoute: typeof AdminConsoleRouteRoute
    }
    '/admin/console/segments/$segmentId/qualified': {
      id: '/admin/console/segments/$segmentId/qualified'
      path: '/segments/$segmentId/qualified'
      fullPath: '/admin/console/segments/$segmentId/qualified'
      preLoaderRoute: typeof AdminConsoleSegmentsSegmentIdQualifiedRouteImport
      parentRoute: typeof AdminConsoleRouteRoute
    }
    '/admin/console/segments/$segmentId/edit': {
      id: '/admin/console/segments/$segmentId/edit'
      path: '/segments/$segmentId/edit'
      fullPath: '/admin/console/segments/$segmentId/edit'
      preLoaderRoute: typeof AdminConsoleSegmentsSegmentIdEditRouteImport
      parentRoute: typeof AdminConsoleRouteRoute
    }
    '/admin/console/pageants/$pageantId/soft-reset': {
      id: '/admin/console/pageants/$pageantId/soft-reset'
      path: '/pageants/$pageantId/soft-reset'
      fullPath: '/admin/console/pageants/$pageantId/soft-reset'
      preLoaderRoute: typeof AdminConsolePageantsPageantIdSoftResetRouteImport
      parentRoute: typeof AdminConsoleRouteRoute
    }
    '/admin/console/awards/$awardId/results': {
      id: '/admin/console/awards/$awardId/results'
      path: '/awards/$awardId/results'
      fullPath: '/admin/console/awards/$awardId/results'
      preLoaderRoute: typeof AdminConsoleAwardsAwardIdResultsRouteImport
      parentRoute: typeof AdminConsoleRouteRoute
    }
    '/admin/console/awards/$awardId/edit': {
      id: '/admin/console/awards/$awardId/edit'
      path: '/awards/$awardId/edit'
      fullPath: '/admin/console/awards/$awardId/edit'
      preLoaderRoute: typeof AdminConsoleAwardsAwardIdEditRouteImport
      parentRoute: typeof AdminConsoleRouteRoute
    }
  }
}

interface AdminConsoleRouteRouteChildren {
  AdminConsoleCandidatesRoute: typeof AdminConsoleCandidatesRoute
  AdminConsoleCollegesRoute: typeof AdminConsoleCollegesRoute
  AdminConsoleDashboardRoute: typeof AdminConsoleDashboardRoute
  AdminConsoleJudgesRoute: typeof AdminConsoleJudgesRoute
  AdminConsolePhasesRoute: typeof AdminConsolePhasesRoute
  AdminConsoleIndexRoute: typeof AdminConsoleIndexRoute
  AdminConsoleAwardsAddRoute: typeof AdminConsoleAwardsAddRoute
  AdminConsoleAwardsIndexRoute: typeof AdminConsoleAwardsIndexRoute
  AdminConsolePageantsIndexRoute: typeof AdminConsolePageantsIndexRoute
  AdminConsoleSegmentsIndexRoute: typeof AdminConsoleSegmentsIndexRoute
  AdminConsoleAwardsAwardIdEditRoute: typeof AdminConsoleAwardsAwardIdEditRoute
  AdminConsoleAwardsAwardIdResultsRoute: typeof AdminConsoleAwardsAwardIdResultsRoute
  AdminConsolePageantsPageantIdSoftResetRoute: typeof AdminConsolePageantsPageantIdSoftResetRoute
  AdminConsoleSegmentsSegmentIdEditRoute: typeof AdminConsoleSegmentsSegmentIdEditRoute
  AdminConsoleSegmentsSegmentIdQualifiedRoute: typeof AdminConsoleSegmentsSegmentIdQualifiedRoute
  AdminConsoleSegmentsSegmentIdScoresRoute: typeof AdminConsoleSegmentsSegmentIdScoresRoute
}

const AdminConsoleRouteRouteChildren: AdminConsoleRouteRouteChildren = {
  AdminConsoleCandidatesRoute: AdminConsoleCandidatesRoute,
  AdminConsoleCollegesRoute: AdminConsoleCollegesRoute,
  AdminConsoleDashboardRoute: AdminConsoleDashboardRoute,
  AdminConsoleJudgesRoute: AdminConsoleJudgesRoute,
  AdminConsolePhasesRoute: AdminConsolePhasesRoute,
  AdminConsoleIndexRoute: AdminConsoleIndexRoute,
  AdminConsoleAwardsAddRoute: AdminConsoleAwardsAddRoute,
  AdminConsoleAwardsIndexRoute: AdminConsoleAwardsIndexRoute,
  AdminConsolePageantsIndexRoute: AdminConsolePageantsIndexRoute,
  AdminConsoleSegmentsIndexRoute: AdminConsoleSegmentsIndexRoute,
  AdminConsoleAwardsAwardIdEditRoute: AdminConsoleAwardsAwardIdEditRoute,
  AdminConsoleAwardsAwardIdResultsRoute: AdminConsoleAwardsAwardIdResultsRoute,
  AdminConsolePageantsPageantIdSoftResetRoute:
    AdminConsolePageantsPageantIdSoftResetRoute,
  AdminConsoleSegmentsSegmentIdEditRoute:
    AdminConsoleSegmentsSegmentIdEditRoute,
  AdminConsoleSegmentsSegmentIdQualifiedRoute:
    AdminConsoleSegmentsSegmentIdQualifiedRoute,
  AdminConsoleSegmentsSegmentIdScoresRoute:
    AdminConsoleSegmentsSegmentIdScoresRoute,
}

const AdminConsoleRouteRouteWithChildren =
  AdminConsoleRouteRoute._addFileChildren(AdminConsoleRouteRouteChildren)

interface JudgeScoringRouteRouteChildren {
  JudgeScoringIndexRoute: typeof JudgeScoringIndexRoute
}

const JudgeScoringRouteRouteChildren: JudgeScoringRouteRouteChildren = {
  JudgeScoringIndexRoute: JudgeScoringIndexRoute,
}

const JudgeScoringRouteRouteWithChildren =
  JudgeScoringRouteRoute._addFileChildren(JudgeScoringRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminConsoleRouteRoute: AdminConsoleRouteRouteWithChildren,
  JudgeScoringRouteRoute: JudgeScoringRouteRouteWithChildren,
  AdminLoginIndexRoute: AdminLoginIndexRoute,
  JudgeLoginIndexRoute: JudgeLoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
