package com.michaelcanonizado.backend.exceptions.common;

public enum ErrorCode {
    ENTITY_NOT_FOUND,
    ENTITY_ALREADY_EXIST,

    PAGEANT_LOCKED,
    PAGEANT_ACCESS_DENIED,
    SEGMENT_NOT_ACTIVE,

    TOKEN_EXPIRED,
    TOKEN_INVALID,
    INVALID_CREDENTIALS,
    UNSUPPORTED_ACCOUNT_TYPE,

    INTERNAL_ERROR,
    INVALID_REQUEST_BODY,
    DATABASE_ERROR
}