package com.michaelcanonizado.backend.exceptions.common;

/* ONLY CHANGE THE PREFIX ENTITY IDENTIFIER */
public enum ErrorCode {
    COLLEGE_NOT_FOUND,
    COLLEGE_ALREADY_EXIST,

    CANDIDATE_NOT_FOUND,
    CANDIDATE_ALREADY_EXIST,

    CRITERION_NOT_FOUND,
    CRITERION_ALREADY_EXIST,

    JUDGE_NOT_FOUND,
    JUDGE_ALREADY_EXIST,

    MANAGER_NOT_FOUND,
    MANAGER_ALREADY_EXIST,

    SEGMENT_NOT_FOUND,
    SEGMENT_ALREADY_EXIST,

    CANDIDATE_SEGMENT_QUALIFICATION_NOT_FOUND,
    CANDIDATE_SEGMENT_QUALIFICATION_ALREADY_EXIST,
    
    SCORE_NOT_FOUND,
    SCORE_ALREADY_EXIST,

    INTERNAL_ERROR
}