package com.michaelcanonizado.backend.exceptions.common;

/* ONLY CHANGE THE PREFIX ENTITY IDENTIFIER */
public enum ErrorCode {
    COLLEGE_NOT_FOUND,
    COLLEGE_ALREADY_EXIST,
    COLLEGE_MISMATCH,

    CANDIDATE_NOT_FOUND,
    CANDIDATE_ALREADY_EXIST,
    CANDIDATE_MISMATCH,

    CRITERION_NOT_FOUND,
    CRITERION_ALREADY_EXIST,
    CRITERION_MISMATCH,

    JUDGE_NOT_FOUND,
    JUDGE_ALREADY_EXIST,
    JUDGE_MISMATCH,

    MANAGER_NOT_FOUND,
    MANAGER_ALREADY_EXIST,
    MANAGER_MISMATCH,

    SEGMENT_NOT_FOUND,
    SEGMENT_ALREADY_EXIST,
    SEGMENT_MISMATCH,
    SEGMENT_FORBIDDEN,

    CANDIDATE_SEGMENT_QUALIFICATION_NOT_FOUND,
    CANDIDATE_SEGMENT_QUALIFICATION_ALREADY_EXIST,
    CANDIDATE_SEGMENT_QUALIFICATION_MISMATCH,

    SCORE_NOT_FOUND,
    SCORE_ALREADY_EXIST,
    SCORE_MISMATCH,

    PAGEANT_NOT_FOUND,
    PAGEANT_ALREADY_EXIST,
    PAGEANT_LOCKED,

    INTERNAL_ERROR,
    INVALID_REQUEST_BODY,
    DATABASE_ERROR
}